import Nav from '@/components/Nav'
import './globals.css'
import { Roboto } from 'next/font/google'

const roboto = Roboto({ subsets: ['latin'], weight: ['400', '700'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }) {
  return (
    <html className='px-4' lang='en'>
      <body className={roboto.className}>
        <Nav />
        {children}
      </body>
    </html>
  )
}
